#!/usr/bin/env bash

xrandr --output eDP1 --mode 1920x1080 --pos 468x611 --rotate normal --output DP1 --off --output HDMI1 --primary --mode 1920x1080 --pos 2388x341 --rotate normal --output HDMI2 --off --output VIRTUAL1 --off
