#!/usr/bin/env bash

#!/usr/bin/env bash

source $(dirname $0)/lib/argparse || exit 1
argparse "$@" <<EOF || exit 1
parser.add_argument('-v', '--video-bitrate', type=int,
                    help='Video bitrate in kbps')

parser.add_argument('-a', '--audio-bitrate', default=32, type=int,
                    help='Audio bitrate in kbps')
EOF

CRF=30

ffmpeg -i "$1" -y -b:v $VIDEO_BITRATE \
  -quality good -crf $CRF -c:v libvpx-vp9 -an \
  -pass 1 -speed 4 -f webm /dev/null &&\
ffmpeg -i "$1" -y -b:v $VIDEO_BITRATE -auto-alt-ref 1 -lag-in-frames 25 \
  -quality good -crf $CRF -c:v libvpx-vp9 -c:a libopus -b:a $AUDIO_BITRATE \
  -pass 2 -speed 1 "$1.webm"
